#!/bin/bash

# Check whether p7zip has been installed
if ! command -v 7z &> /dev/null; then
    echo "Error: p7zip didn't install!!"
    echo "Please use the following commands to install:"
    echo "Debian/Ubuntu： sudo apt install p7zip-full"
    echo "Arch Linux： sudo pacman -S p7zip"
    echo "macOS (Homebrew）： brew install p7zip"
    exit 1
fi

# The action
echo "Choose your action:"
echo "1) Compress"
echo "2) Decompress"
read -p "What do you want to do (1 or 2) ? " action
echo

# Check the user's input
if [[ "$action" != "1" && "$action" != "2" ]]; then
    echo "Not an available action or input, the program will end it now!"
    exit 1
fi

# The desination and source
if [[ "$action" == "1" ]]; then
    read -p "Please enter the file's (full) path:" source
    read -p "Please enter the file's destination and it's name:" destination
else
    read -p "Please enter the file's (full) path: " source
    read -p "Please enter the file's destination (default -> current directory): " destination
fi

# Compress format
if [[ "$action" == "1" ]]; then
    echo "Choose your format:"
    echo "1) 7z"
    echo "2) zip"
    echo "3) tar"
    read -p "What do you want to do (1-3)? " format

    case "$format" in
        1) format="7z" ;;
        2) format="zip" ;;
        3) format="tar" ;;
        *)
            echo "Wrong input, the program will end it now!"
            exit 1
            ;;
    esac
fi

# Password
password_flag=""
if [[ "$action" == "1" ]]; then
    read -p "Do you want to set password (y/n):" use_password
    if [[ "$use_password" == "y" || "$use_password" == "Y" ]]; then
        read -s -p "Please enter the password:" password
        echo
        password_flag="-p$password"
    fi
fi

# The process
if [[ "$action" == "1" ]]; then
    echo "Compressing..."
    7z a "$destination" "$source" $password_flag
else
    echo "Decompressing..."
    if [[ -z "$destination" ]]; then
        7z x "$source" $password_flag
    else
        7z x "$source" -o"$destination" $password_flag
    fi
fi

if [[ $? -eq 0 ]]; then
    echo "Done!"
else
    echo "Failure, please check your input!"
fi
